# Generated by Django 4.0.4 on 2022-05-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.TextField()),
                ('real_name', models.TextField()),
                ('user_id', models.TextField()),
            ],
        ),
    ]
